name: Run Buildkite

on:
  workflow_dispatch:

jobs:
  buildkite:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "<>"

      - name: Checkout repository
        uses: actions/checkout@v3