name: Cut a Release

on:
  workflow_dispatch:
    inputs:
      release-branch-suffix:
        description: 'Suffix for the release branch (e.g., 20250509)'
        required: true
      tag:
        description: 'Tag for the release (e.g., v1.0.0)'
        required: true

jobs:
  create-release-branch:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "<>"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update develop branch
        run: |
          git fetch origin develop
          git checkout develop
          git pull origin develop

      - name: Create release branch
        run: |
          git checkout -b releases/${{ github.event.inputs.release-branch-suffix }} develop
          git push origin HEAD

      - name: Create release PR using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr create \
            --title "Release: ${{ github.event.inputs.tag }}" \
            --body "This PR merges the release branch into main." \
            --base main \
            --head releases/${{ github.event.inputs.release-branch-suffix }}

      - name: Generate changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          project: ${{ github.event.repository.name }}
          output: CHANGELOG.md
          releaseBranch: 'releases/${{ github.event.inputs.release-branch-suffix }}'
          futureRelease: ${{ github.event.inputs.tag }}
          excludeLabels: 'duplicate,question,invalid,wontfix,help wanted'
          issues: true
          pullRequests: true
          addSections: '{"Product Notes": {"labels": ["product update"]}}'

      - name: Commit changelog to release branch
        run: |
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for ${{ github.event.inputs.tag }}"
          git push origin HEAD

      - name: Create tag
        run: |
          git tag -a ${{ github.event.inputs.tag }} -m "Release ${{ github.event.inputs.tag }}"
          git push origin --tags