name: Finalize a Release

on:
  workflow_dispatch:

jobs:
  finalize-release:
    runs-on: ubuntu-latest

    steps:
      - name: Configure Git user
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "<>"

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Merge release branch into main using GitHub CLI
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PR_NUMBERS=$(gh pr list --state open --head releases/* --json number -q '.[].number')
          PR_COUNT=$(echo "$PR_NUMBERS" | wc -l)
          if [ "$PR_COUNT" -gt 1 ]; then
            echo "More than 1 release PR is open. Exiting workflow."
            exit 1
          elif [ "$PR_COUNT" -eq 1 ]; then
            PR_NUMBER=$(echo "$PR_NUMBERS" | head -n 1)
            gh pr merge $PR_NUMBER --merge --delete-branch --body "Merging release branch into main."
          else
            echo "No open pull request found for the release branch."
          fi

      - name: Merge main into develop
        run: |
          git checkout develop
          git merge --no-ff main -m "Sync main into develop"
          git push origin develop