name: Generate CHANGELOG

on:
  push:
    tags:
      - 'v*'  # Triggers on version tags like v1.0.0

jobs:
  generate-changelog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate changelog
        uses: janheinrichmerker/action-github-changelog-generator@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: ${{ github.repository_owner }}
          project: ${{ github.event.repository.name }}
          output: CHANGELOG.md
          releaseBranch: 'releases/*'
          futureRelease: ${{ github.ref_name }}
          excludeLabels: 'duplicate,question,invalid,wontfix,help wanted'
          issues: true
          pullRequests: true

      - name: Commit changelog
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add CHANGELOG.md
          git commit -m "chore: update CHANGELOG for ${{ github.ref_name }}"
          git pull origin develop --no-rebase
          git push origin HEAD:develop
